# IRP SiamMOT Tracker

MODEL:
  USE_FASTER_RCNN: False
  TRACK_ON: True
  
INPUT:
  MIN_SIZE_TRAIN: 640
  MAX_SIZE_TRAIN: 960
  
  BACKBONE: 
    WEIGHT: "siammot/weight/DLA34_backbone.pt"

  RPN: 
    WEIGHT: "siammot/weight/RPN.pt"

  ROI_BOX_HEAD: 
    WEIGHT: "siammot/weight/box_head.pt"
    
SOLVER:
  BASE_LR: 0.5
  CHECKPOINT_PERIOD: 1